### ISSUE TITLE
Error in "Use embedded signing" using JWT

### ISSUE THREAD

**Issue by Rafalkufel** [docusign/code-examples-python#22]
Exploring first example ("Use embedded signing") with JWT option i came across an error with redirect after return from https://account-d.docusign.com/ domain:

```
127.0.0.1 - - [27/Nov/2020 13:55:36] "GET /ds/callback?code=eyJ0eXXXXXXXNVCIsImFsZyI6IlJTMjU-------exemplary_access_token------------9MYriQVAAEAAAAYAAImtjA HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/rafal/code/Testapp-python/app/docusign/views.py", line 40, in ds_callback
    resp = DSClient.get_token(session["auth_type"])
  File "/home/rafal/code/Testapp-python/app/docusign/ds_client.py", line 143, in get_token
    resp = cls.get(auth_type).to_dict()
AttributeError: 'NoneType' object has no attribute 'to_dict'

.... and consent grant process cannot be finished

ubuntu 20.04
python 3.8.5
flask 1.1.1
docusign-esign 3.6.0
```

**Comment by ivdinkovds** [comment]
I am sorry you are having this issue. Thank you for notifying us.

**Comment by Rafalkufel** [comment]
It seems that this PR https://github.com/docusign/code-examples-python/pull/23 with slight correction would solve issue

`from urllib.parse import quote` - at the beginning

`consent_scopes = quote(" ".join(use_scopes))` - line 102

**Comment by InbarGazit** [comment]
This issue has been resolved.
